### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by FrankBishop** [FrankBishop/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List
- [x] create a document.querySelector for the car
- [x] create classes for each direction the car can be turned in
- [x] Create a simple data model that includes which way the car is facing, (north, south, east, or west).
- [x] create a function for turning the car 
![image](https://user-images.githubusercontent.com/75149451/108412697-f27eb280-71de-11eb-8af7-61c44ca30b2b.png)
