### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by FrankBishop** [FrankBishop/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add a location to your data model to hold the car's x and y coordinates on the page.
- [x] Set positioning for image and container 
- [x] Add function for car to move across screen
- ![image](https://user-images.githubusercontent.com/75149451/108412759-09bda000-71df-11eb-95d6-fe97e530a3c0.png)
