### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by FrankBishop** [FrankBishop/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [ ] Build if/else for className of car that determines what direction it is facing
- [ ] build moveLeft, moveRight, and moveUp functions
- [ ] test all functionality 
![image](https://user-images.githubusercontent.com/75149451/108412849-28bc3200-71df-11eb-9e6b-3e545de3c076.png)
